### ISSUE TITLE
Mutiple chats

### ISSUE THREAD

**Issue by Migarve55** [Arquisoft/dechat_en1b#28]
As for now, we do not have a way to send chat to multiple contacts.

This is a complex issue because several things need to be checked:

- [x]  If a user does not have the correct file structure "/dechat/chat_xxx_yyy" it needs to be created

- [x]  The files permisions need to be right so you can read another contact message log. (use the .acl)

- [x] The messages should be loaded in the correct order (use the timestamp) anytime you click a contact in the list.

**Comment by Migarve55** [comment]
I have added the basic code for this. The code now works like this:

- Sender: Enrique
- Reciever: Paco

Paco's POD structure: 
`https://paco.solid.community/private/dechat/chat_enrique/`
Contains all the messages sent by Paco to Enrique.

Enrique's POD structure: 
`https://enrique.solid.community/private/dechat/chat_paco/`
Contains all the messages sent by Enrique to Paco.

This is very important. If you want to test this, and test further commits, please create this file structure inside your pod. Otherwise, this will not work at all.

**Comment by Nacho888** [comment]
I didn't notice this folder structure, I've just created it like "/private/dechat/chat" so I'm going to change the method to append also "_nameOfTheConversation".

**Comment by Nacho888** [comment]
The folder structure creation maybe needs some refactoring but in addition we have to take into account that the URIs should be composed taking into account other POD providers apart from Solid Community sucha as Inrupt. 

That's because our URI generation only takes into account WebIDs with the structure `https://ejemplo.solid.community/...` 

And it must also capable to process WebIDs such as `https://ejemplo.inrupt.net/...`

**Comment by Migarve55** [comment]
You are right, however, this is a temporal solution. We need to get this done, but in the future, we could add a field in our card profile that links the chat location. This could be another issue.
